avatar: https://benben-miao.gitee.io/image-cloud/BioBlog/avatar.jpg
background: # æ—¢æ˜¯åšå®¢çš„èƒŒæ™¯ï¼Œåˆæ˜¯æ–‡ç« é»˜è®¤å¤´å›¾
    path: 
    width: 1280
    height: 1080
favicon:
  href: https://benben-miao.gitee.io/image-cloud/BioBlog/avatar.jpg # ç½‘ç«™å›¾æ ‡
  type: image/png # å›¾æ ‡ç±»å‹ï¼Œå¯èƒ½çš„å€¼æœ‰(image/png, image/vnd.microsoft.icon, image/x-icon, image/gif)

function: # åŠŸèƒ½å¼€å…³ï¼Œå¯é€‰å€¼ï¼ˆtrue,falseï¼‰
  globalToc: true # å¼€å¯è¯¥åŠŸèƒ½ä¼šè‡ªåŠ¨å¼€å¯æ–‡ç«  TOCï¼ˆæ–‡ç« ç›®å½•ï¼‰ åŠŸèƒ½
  wordCount: true # æ˜¯å¦å¼€å¯æ–‡ç« å­—æ•°ç»Ÿè®¡ (true, false)

imageCDN: # å›¾ç‰‡ CDN åŠŸèƒ½
  enable: false # å¼€å¯è¯¥åŠŸèƒ½  
  origin: /../../images/ # å›¾ç‰‡åŸå§‹ç›®å½•
  to: https://cdn.jsdelivr.net/gh/nexmoe/nexmoe.github.io@latest/images/ # å›¾ç‰‡ CDN åŸŸå

# è‡ªå®šä¹‰æ ·å¼ï¼Œå¯ç”¨åå¯åœ¨ç«™ç‚¹çš„sourceæ–‡ä»¶å¤¹ä¸‹æ–°å»ºcustom.cssè‡ªå®šä¹‰ç«™ç‚¹æ ·å¼
customStyles:
  - custom.css
  
# é™„åŠ å›¾æ ‡åº“ ä½¿ç”¨è¯´æ˜ï¼šhttps://docs.nexmoe.com/config/icon
iconlib: # //at.alicdn.com/t/font_1038733_0xvrvpg9c0r.css

menu:
  Home: 
    - /
    - icon-home
  BioBlog: 
    - /bioblog
    - icon-coffee
  About:
    - /about.html
    - icon-info-circle

widgets:
    - name: search
      enable: true
      options: 
        search: 
            type: engine # å¯é€‰engineï¼ˆç”¨æœç´¢å¼•æ“æœç´¢ï¼‰ã€swiftypeã€æˆ–localï¼ˆæœ¬åœ°æœç´¢ï¼‰
            url: https://cn.bing.com/search?q=site:nexmoe.com # æœç´¢å¼•æ“åœ°å€ï¼Œåœ¨typeä¸ºswiftypeæ—¶æ— æ•ˆ e.g:https://www.google.com/search?q={ä½ çš„åšå®¢é“¾æ¥}
            id: <swiftype-id> # swiftypeçš„idï¼Œè§å¯ç”¨æ•™ç¨‹ã€‚åœ¨typeä¸ºengineæ—¶æ— æ•ˆ
    - name: social
      enable: true
      options: 
        social:
            GitHub:
              - https://github.com/benben-miao
              - icon-github
              - rgb(25, 23, 23)
              - rgba(25, 23, 23, .15)
            Gitee:
              - https://gitee.com/benben-miao
              - icon-container
              - rgb(25, 23, 23)
              - rgba(25, 23, 23, .15)
            Hiplot-Cloud:
              - https://hiplot.com.cn
              - icon-dribbble
              - rgb(25, 23, 23)
              - rgba(25, 23, 23, .15)
            Bio-Nav:
              - https://bio-nav.hiplot.com.cn
              - icon-battlenet
              - rgb(25, 23, 23)
              - rgba(25, 23, 23, .15)
            Colors-Cloud:
              - https://colors-cloud.onrender.com
              - icon-calendar-fill
              - rgb(25, 23, 23)
              - rgba(25, 23, 23, .15)
            YuQue:
              - https://www.yuque.com/benben.miao
              - icon-home
              - rgb(25, 23, 23)
              - rgba(25, 23, 23, .15)
            Dev-Wall:
              - https://hiplot.com.cn/developer-wall
              - icon-coffee
              - rgb(25, 23, 23)
              - rgba(25, 23, 23, .15)
            OmicsSphere:
              - https://omicspheremed.netlify.app/
              - icon-areachart
              - rgb(25, 23, 23)
              - rgba(25, 23, 23, .15)
    - name: category
      enable: true
    - name: tagcloud
      enable: true
      options: 
        maxTagcloud: 30  # æ ‡ç­¾äº‘ç»„ä»¶æ˜¾ç¤ºçš„æ ‡ç­¾æ•°é‡ï¼Œ0 è¡¨ç¤ºä¸é™åˆ¶
    - name: hitokoto # ä¸€è¨€ widget
      enable: false
      options: 
        widgetHitokoto: # ä¸€è¨€ç»„ä»¶
            loading_placeholder: 'ğŸš€ è·å–ä¸­...' # æ­£åœ¨ä¸€è¨€æ—¶çš„å ä½ç¬¦
            loading_error_placeholder: 'ğŸ è·å–å¤±è´¥...' # åŠ è½½ä¸€è¨€å¤±è´¥æ—¶çš„å ä½ç¬¦
            category: # ä¸€è¨€å¥å­ç±»å‹ï¼ˆå¯é€‰ï¼‰ï¼Œä¸é…ç½®çš„è¯éšæœºè·å–ï¼Œè¯¦è§ https://developer.hitokoto.cn/sentence/#%E5%8F%A5%E5%AD%90%E7%B1%BB%E5%9E%8B-%E5%8F%82%E6%95%B0
    - name: archive #settings: widgetAchive
      enable: true
      options:
        widgetAchive: #æ–‡ç« å½’æ¡£ç»„ä»¶
            archive_type: 'month' #æŒ‰æœˆå±•ç¤ºè¿˜æ˜¯æŒ‰å¹´å±•ç¤º
            show_count: true  #æ˜¯å¦å±•ç¤ºæ•°é‡
    - name: recent_posts
      enable: true
    - name: link #settings: widgetLink
      enable: true
      options: 
        widgetLink: #é“¾æ¥ç»„ä»¶
            - title: Hiplot
              img: https://benben-miao.gitee.io/image-cloud/BioBlog/hiplot-native.png
              link : https://hiplot.com.cn
            - title: BioSciTools
              img: https://benben-miao.gitee.io/image-cloud/BioSciTools/BioSciTools-Home.png
              link : https://bioscitools.github.io

copyTip: '<strong>Copyrightï¼š</strong>benben-miao <a href="https://github.com/benben-miao" target="_blank">https://github.com/benben-miao</a>'